language: java
sudo: false
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  file: build/libs/xld-datapower-plugin-1.0.0.jar
  skip_cleanup: true
  api-key:
    secure: CWdIY7h9TlLJNO1ykeOj1xq/n3XDzFoMaQiWq6RpWvkWh2agpKwooqC3YPnK4ZuXzcR9dH6igeYc5KmjZyHAKnMHml9ROm+2p8Lo9qJNYnkpKyQB0xedEdcPdvWBNRiS4PAz1g3FxY0En7N3QI9gicbNqyIuMd4dskrlHVSd49MAEho7rvQKemQgEWrGNC4Ax0s/BrFa7nicMkUT7IdOTdwkrBCi7bGalRsEmyFj9VNboqH9WvbSE+nHpC2onf1g/96Ob/WxNVFw/Sseye4fZmGRVviw9mK4XccBtSXZTMAMV0guv9fQWVyqGG05wg4dvdvfdUC9Hv0YKSQe/oOQei/aksKbwb52nbfXqUPWY+aIBhqOnV7qVkMcGukyuJ02BWauJGxHh8GIZlBbA4/FARohqOlXPy4XLaRaW6qTMP3kVENqmMWQJP6JuTOeX80U+yXM7CJpROpJ1GlFXIdXkQTBdfleBd9hrXUzpug+tGkB4zUMsw+SkGGgF7eb6YnkCpizjbKHXs9lC3zBAvSQMYM4V/qo4bpw1uX3tjkhDurjB3QjMcv02Lg8sPUqrprK/Yo4BNYKA+PVgWTuWMb+xLNiZMTf9435AYlieZjYsvj3lnhmxj+6TZe6kjDb2XM4Hd+HbPOnWrNhsudvudsJ26CPfB0cvOV0HwiEJ1RIBBY=
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-datapower-plugin